# Generated by Django 3.0.5 on 2020-04-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
