# Generated by Django 3.0.5 on 2020-04-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200416_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='price',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='price_card',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='price_event',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='price_internet',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
