# Generated by Django 3.0.5 on 2020-04-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
