# Generated by Django 3.0.5 on 2020-04-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_updatenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updates_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
